### ISSUE TITLE
Add search to your index action in Rails

### ISSUE THREAD

**Issue by anhpnguyen** [anhpnguyen/tc359_rails_final#3]

**Comment by anhpnguyen** [comment]
@chrisvfritz Hi Chris! I'm trying to add a simple search for the single model 'story' using this tutorial http://railscasts.com/episodes/37-simple-search-form/ . However the search box didn't show up in story's index action.

**Comment by anhpnguyen** [comment]
@chrisvfritz Hi Chris! I'm trying to add a simple search for the single model 'story' using this tutorial http://railscasts.com/episodes/37-simple-search-form/ . However the search box didn't show up in story's index action.

**Comment by chrisvfritz** [comment]
I just left [a notes here](https://github.com/anhpnguyen/tc359_rails_final/commit/124a29f9a63b23003759fbb999daa6a872162b01#diff-2) regarding this.
